- name: Configure HAProxy
  hosts: haproxy
  remote_user: ubuntu
  become: yes
  gather_facts: False
  pre_tasks:
      # - name: Set APT proxy
      # raw: echo "Acquire::HTTP::Proxy
      # \"http://omistack-storage.e-technik.uni-ulm.de:3142\";" > /etc/apt/apt.conf.d/01proxy
    - name: install python2
      raw: apt-get -y update && apt-get -y install python-minimal
  tasks:
    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=3600
    - name: Install haproxy
      apt: name=haproxy state=present
    - name: Enable init script
      replace: dest='/etc/default/haproxy'
        regexp='ENABLED=0'
        replace='ENABLED=1'
    - name: Update HAProxy config
      template: src=templates/haproxy.cfg.j2
        dest=/etc/haproxy/haproxy.cfg
      notify:
      - restart haproxy

  handlers:
    - name: restart haproxy
      service: name=haproxy state=restarted
