- name: Configure Web Servers
  hosts: webservers
  remote_user: ubuntu
  become: yes
  gather_facts: False
  pre_tasks:
      # - name: Set APT proxy
      # raw: echo "Acquire::HTTP::Proxy
      # \"http://omistack-storage.e-technik.uni-ulm.de:3142\";" > /etc/apt/apt.conf.d/01proxy
    - name: install python2
      raw: apt-get -y update && apt-get -y install python-minimal
  tasks:
    - name: Ensure Apache is installed
      apt: name=apache2 state=latest
    - name: Ensure that Apache is started
      service: name=apache2 state=started
- name: Gathering facts about webservers
  hosts: webservers
  remote_user: ubuntu
  become: yes
  tasks:
    - name:  Gathering facts
      setup:
