---
- name: Create the router "{{ router_name }}"
  os_router:
    state: present
    name: "{{ router_name }}"
    network: "{{ ext_nw_name }}"
    interfaces:
        - "{{ interface_name }}"
    verify: false
