# debug template:
#
# - hosts: localhost
# gather_facts: false
# tasks:
# - debug:
# var:
# hostvars['localhost']['ecorz_nw'].id
---
- hosts: localhost
  gather_facts: false
  vars:
      nw_name: "{{ nw_name_par }}"
  tasks:
    - name: create network
      include_role:
        name: create_network
- hosts: localhost
  gather_facts: false
  vars:
    subnet_name: "{{ subnet_name_par }}"
    nw_id: "{{ hostvars['localhost']['ecorz_nw'].id }}"
  tasks:
    - name: create subnet
      include_role:
        name: create_subnet
- hosts: localhost
  gather_facts: false
  vars:
    router_name: "{{ router_name_par }}"
    interface_name: ecorz_subnet
  roles:
    - create_router
- hosts: localhost
  gather_facts: false
  vars:
      sec_group_name: "{{ sec_group_name_ans }}"
  roles:
    - create_security_group
- hosts: localhost
  gather_facts: false
  vars:
      sec_group_name: "{{ sec_group_name_ans }}"
      port_nmbr: "{{ port_nmbr_ssh }}"
  roles:
    - create_rule
- hosts: localhost
  gather_facts: false
  vars:
    sec_group_name: "{{ sec_group_name_webs }}"
  roles:
    - create_security_group
- hosts: localhost
  gather_facts: false
  vars:
    sec_group_name: "{{ sec_group_name_webs }}"
    port_nmbr: "{{ port_nmbr_web }}"
  roles:
    - create_rule
- hosts: localhost
  gather_facts: false
  tasks:
    - name: tmp deploy webservers in az1
      vars:
        webs_name: "{{ item }}"
        nw_name: ecorz_nw
        sec_group_list: [default,ansible,webserver]
        az: "{{ az1 }}"
      include_role:
        name: deploy_webserver
      loop:
        "{{ groups['webservers_az1'] }}"
- hosts: localhost
  gather_facts: false
  tasks:
    - name: tmp deploy webservers in az2
      vars:
        webs_name: "{{ item }}"
        nw_name: ecorz_nw
        sec_group_list: [default,ansible,webserver]
        az: "{{ az2 }}"
      include_role:
        name: deploy_webserver
      loop:
        "{{ groups['webservers_az2'] }}"
- hosts: localhost
  gather_facts: false
  tasks:
    - name: tmp deploy haproxy
      vars:
        haproxy_name: "{{ item }}"
        nw_name: ecorz_nw
        sec_group_list: [default,ansible,webserver]
      include_role:
        name: deploy_haproxy
      loop:
        "{{ groups['haproxies'] }}"
- hosts: webservers_az1:webservers_az2:haproxies
  gather_facts: false
  roles:
    - wait_for_port1_ready
- hosts: webservers_az1:webservers_az2
  gather_facts: false
  pre_tasks:
    - import_tasks: inst_python_task.yml
  roles:
    - config_webservers
- hosts: haproxies
  gather_facts: false
  pre_tasks:
    - import_tasks: inst_python_task.yml
  roles:
    - config_haproxy
