---
- hosts: localhost
  gather_facts: false
  vars:
      register_name: "{{ nw_register_name }}"
  roles:
    - create_network
- hosts: localhost
  gather_facts: false
  vars:
      nw_id: "{{ nw_register_name.id }}"
      register_name: "{{ subnet_register_name }}"
  roles:
    - create_subnet
- hosts: localhost
  gather_facts: false
  vars:
      interface_name: "{{ subnet_register_name }}"
  roles:
    - create_router
- hosts: localhost
  gather_facts: false
  vars:
      sec_group_name: "{{ sec_group_name_ans }}"
  roles:
    - create_security_group
- hosts: localhost
  gather_facts: false
  vars:
      sec_group_name: "{{ sec_group_name_ans }}"
      port_nmbr: "{{ port_nmbr_ssh }}"
  roles:
    - create_rule
- hosts: localhost
  gather_facts: false
  vars:
    sec_group_name: "{{ sec_group_name_webs }}"
  roles:
    - create_security_group
- hosts: localhost
  gather_facts: false
  vars:
    sec_group_name: "{{ sec_group_name_webs }}"
    port_nmbr: "{{ port_nmbr_webs }}"
  roles:
    - create_rule
- hosts: localhost
  gather_facts: false
  vars:
    webs_name: "{{ item.name }}"
    nw_name: "{{ nw_register_name }}"
    sec_group_list:
        sec_group1: default
        sec_group2: ansible
        sec_group3: webserver
    az: "{{ az1 }}"
  tasks:
    - name: tmp deploy webservers in az1
      include_role:
        name: deploy_webserver
      loop:
        "{{ webservers_az1 }}"
- hosts: localhost
  gather_facts: false
  vars:
    webs_name: "{{ item.name }}"
    nw_name:  "{{ nw_register_name }}"
    sec_group_list:
        sec_group1: default
        sec_group2: ansible
        sec_group3: webserver
    az: "{{ az2 }}"
  tasks:
    - name: tmp deploy webservers in az2
      include_role:
        name: deploy_webserver
      loop:
        "{{ webservers_az2 }}"
- hosts: localhost
  gather_facts: false
  vars:
    haproxy_name: "{{ item.name }}"
    nw_name: "{{ nw_register_name }}"
    sec_group_list:
        sec_group1: default
        sec_group2: ansible
        sec_group3: webserver
  tasks:
    - name: tmp deploy haproxy
      include_role:
        name: deploy_haproxy
      loop:
          "{{ haproxies }}"
- hosts: webservers:haproxies
  gather_facts: false
  roles:
    - wait_for_port1_ready
- hosts: webservers
  gather_facts: false
  pre_tasks:
    - import_tasks: inst_python_task.yml
  roles:
    - config_webservers
- hosts: haproxies
  gather_facts: false
  pre_tasks:
    - import_tasks: inst_python_task.yml
  roles:
    - config_haproxy
