# debug template:
#
# - hosts: localhost
# gather_facts: false
# tasks:
# - debug:
# var:
# hostvars['localhost']['ecorz_nw'].id
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: create network
      vars:
        nw_name: "{{ nw_name_par }}"
      include_role:
        name: create_network
    - name: create subnet
      vars:
        subnet_name: "{{ subnet_name_par }}"
        nw_id: "{{ hostvars['localhost']['ecorz_nw'].id }}"
      include_role:
        name: create_subnet
    - name: create router
      vars:
        router_name: "{{ router_name_par }}"
        interface_name: ecorz_subnet
      include_role:
        name: create_router
    - name: create security group
      vars:
        sec_group_name: "{{ sec_group_name_ans }}"
      include_role:
        name: create_security_group
    - name: create security group rule
      vars:
        sec_group_name: "{{ sec_group_name_ans }}"
        port_nmbr: "{{ port_nmbr_ssh }}"
      include_role:
        name: create_rule
    - name: create security group
      vars:
        sec_group_name: "{{ sec_group_name_webs }}"
      include_role:
        name: create_security_group
    - name: create security group rule
      vars:
        sec_group_name: "{{ sec_group_name_webs }}"
        port_nmbr: "{{ port_nmbr_web }}"
      include_role:
        name: create_rule

- hosts: localhost
  gather_facts: true
  tasks:
    - name: Deploy webservers in az1
      vars:
        webs_name: "{{ item }}"
        nw_name: ecorz_nw
        sec_group_list: [default,ansible,webserver]
        az: "{{ az1 }}"
      include_role:
        name: deploy_webserver
      loop:
        "{{ groups['webservers_az1'] }}"
    - name: Deploy webservers in az2
      vars:
        webs_name: "{{ item }}"
        nw_name: ecorz_nw
        sec_group_list: [default,ansible,webserver]
        az: "{{ az2 }}"
      include_role:
        name: deploy_webserver
      loop:
        "{{ groups['webservers_az2'] }}"
    - name: Deploy haproxy
      vars:
        haproxy_name: "{{ item }}"
        nw_name: ecorz_nw
        sec_group_list: [default,ansible,webserver]
      include_role:
        name: deploy_haproxy
      loop:
        "{{ groups['haproxies'] }}"

- hosts: webservers_az1:webservers_az2:haproxies
  gather_facts: false
  roles:
    - wait_for_port1_ready

- hosts: webservers_az1:webservers_az2
  gather_facts: false
  pre_tasks:
    - import_tasks: inst_python_task.yml
  roles:
    - config_webservers

- hosts: haproxies
  gather_facts: false
  pre_tasks:
    - import_tasks: inst_python_task.yml
  roles:
    - config_haproxy
