- name: Update apt cache
  remote_user: ubuntu
  become: yes
  apt: update_cache=yes cache_valid_time=3600

- name: Install haproxy
  remote_user: ubuntu
  become: yes
  apt: name=haproxy state=present

- name: Enable init script
  remote_user: ubuntu
  become: yes
  replace: dest='/etc/default/haproxy'
    regexp='ENABLED=0'
    replace='ENABLED=1'

- name: Update HAProxy config
  remote_user: ubuntu
  become: yes
  template: src=templates/haproxy.cfg.j2
    dest=/etc/haproxy/haproxy.cfg
  notify:
    - restart haproxy
