---
- name: Deploy HAProxy Instance
  os_server:
    state: present
    name: "{{ haproxy_name }}"
    image: ubuntu-1804
    key_name: id_rsa_omistack
    timeout: 200
    flavor: medium
    network: "{{ nw_name }}"
    security_groups: {{ sec_group_list|join(',') }}
    verify: false
