- name: Ensure Apache is installed
  remote_user: ubuntu
  become: yes
  apt:
    name: apache2
    state: latest
    update_cache: yes

- name: Ensure that Apache is started
  remote_user: ubuntu
  become: yes
  service: name=apache2 state=started

- name: Gathering facts about webservers
  remote_user: ubuntu
  become: yes
  setup:
