---
- name: Deploy Webserver Instance "{{ webs_name }}" in "{{ az }}"
  os_server:
    state: present
    name: "{{ webs_name }}"
    image: ubuntu-1804
    key_name: id_rsa_omistack
    timeout: 200
    flavor: small
    network: "{{ nw_name }}"
    security_groups: "{{ sec_group_list|join(',') }}"
    availability_zone: "{{ az }}"
    verify: false
  register: webservers_az
- name: Persist register-variable for upstream use
  set_fact:
    register_upstream: "{{ register_upstream + [webservers_az] }}"
