---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Uneploy webservers in az1
      vars:
        webs_name: "{{ webserver_pref_az1 }}_{{ item }}"
        exclusive_loop_end: "{{ webserver_az1_count|int + 1}}"
      include_role:
        name: delete_webserver
      loop: "{{ range(1, exclusive_loop_end|int, 1)|list|default([]) }}"
      when: webserver_az1_count|int > 0
    - name: Undeploy webservers in az2
      vars:
        webs_name: "{{ webserver_pref_az2 }}_{{ item }}"
        exclusive_loop_end: "{{ webserver_az2_count|int + 1}}"
      include_role:
        name: delete_webserver
      loop: "{{ range(1, exclusive_loop_end|int, 1)|list|default([]) }}"
      when: webserver_az2_count|int > 0
    - name: Undeploy haproxy
      vars:
        haproxy_name: "haproxy_{{ item }}"
      include_role:
        name: delete_haproxy
      with_sequence: start=1 end=1
