- hosts: docker_containers_medium:docker_containers_xlarge
  remote_user: ubuntu
  become: yes
  gather_facts: false
  vars:
    container_name_: "{{ container_name }}"
  roles:
    - destroy_container
